version: 0.2

phases:
  pre_build:
    commands:
      - cd sample/client
      - npm install
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./dist s3://plecong.site.s3-website-us-east-1.amazonaws.com/
artifacts:
  files:
    - '**/*'
  base-directory: sample/client/dist