version: 0.2

phases:
  pre_build:
    commands:
      - cd sample/client
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - 'dist/**/*'
    - 'buildspec-deploy.yml'
  base-directory: sample/client