version: 0.2

phases:
  install:
    commands:
      - cd sample/client
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: sample/client/dist